# Generated by Django 4.0.5 on 2023-04-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiles',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('launch_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('L', 'Live'), ('P', 'Pending'), ('A', 'Archived')], default='L', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.TextField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tiles')),
            ],
        ),
    ]
