# Generated by Django 4.0.5 on 2023-04-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Tiles',
            new_name='Tile',
        ),
    ]
